import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { Newsreader } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const newsreader = Newsreader({
  subsets: ["latin"],
  variable: "--font-serif",
});

export const metadata = {
  title: "Citizen Dashboard",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-[#E0F2FE] font-sans ${inter.variable}`}>
        {children}
      </body>
    </html>
  );
}
